language: ruby
cache:
- bundler
sudo: false
rvm:
- 2.2.2
services:
- mysql
before_script:
- mysql -e 'create database wheelmap_test;'
- mysql wheelmap_test < db/structure.sql
- cp config/database.SAMPLE.yml config/database.yml
- cp config/open_street_map.SAMPLE.yml config/open_street_map.yml
- cp config/newrelic.SAMPLE.yml config/newrelic.yml
- cp config/application.yml.sample config/application.yml
branches:
  only:
  - master
notifications:
  email:
  - developers@sozialhelden.de
