embed_assets: off

javascripts:
  default:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-migrate-1.1.1.js
    - public/javascripts/jquery.tools.js
    - public/javascripts/jquery.blockUI.js
    - public/javascripts/jquery.uploadify.js
    - public/javascripts/jquery.lightbox.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/openlayers211.js
    - public/javascripts/openlayers_i18n.js
    - public/javascripts/osm.js
    - public/javascripts/cookie.js
    - public/javascripts/uservoice.js
    - public/javascripts/json2.js
    - public/javascripts/filter_settings.js
    - public/javascripts/splash.js
    - public/javascripts/application.js

  relaunch:
    - public/javascripts/jquery.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery.parsequery.js
    - public/javascripts/leaflet.js
    - public/javascripts/cookie.js
    - public/javascripts/handlebars.js
    - public/javascripts/map.js

  modernizr:
    - public/javascripts/modernizr.js

  ie:
    - public/javascripts/html5.js

stylesheets:

  active_admin:
    - public/stylesheets/active_admin.css

  screen:
    - public/stylesheets/screen.css
    - public/theme/default/style.css

  relaunch:
    - public/stylesheets/relaunch.css
    - public/stylesheets/leaflet.css

  relaunch.ie:
    - public/stylesheets/leaflet.ie.css

  node:
    - public/stylesheets/node.css
    - public/stylesheets/uploadify.css
    - public/stylesheets/jquery.lightbox.css
    - public/theme/default/style.css
