embed_assets: off

javascripts:
  default:
    - public/javascripts/jquery.js
    - public/javascripts/jquery.tools.js
    - public/javascripts/openlayers211.js
    - public/javascripts/openlayers_i18n.js
    - public/javascripts/osm.js
    - public/javascripts/cookie.js
    - public/javascripts/uservoice.js
    - public/javascripts/json2.js
    - public/javascripts/filter_settings.js
    - public/javascripts/application.js
    
stylesheets:
  screen:
    - public/stylesheets/screen.css
    
  node:
    - public/stylesheets/node.css
