production:
  user: osm_username
  password: osm_password
  oauth_secret: ''
  oauth_key: ''
  oauth_site: 'http://www.openstreetmap.org'
  xapi_site: 'http://www.informationfreeway.org'

development:
  user: osm_username
  password: osm_password
  oauth_secret: '***REMOVED***'
  oauth_key: '***REMOVED***'
  # oauth_site: 'http://api06.dev.openstreetmap.org'
  oauth_site: 'http://www.openstreetmap.org'
  xapi_site: 'http://www.informationfreeway.org'
  
test:
  user: osm_username
  password: osm_password
  oauth_secret: ''
  oauth_key: ''
  oauth_site: 'http://api06.dev.openstreetmap.org'

cucumber:
  user: schmerzbereiter
  password: ***REMOVED***
  oauth_secret: ''
  oauth_key: ''
  oauth_site: 'http://api06.dev.openstreetmap.org'